version: "3"
services:

  node:
    image: node
    container_name: oauth2
    env_file: .env
    working_dir: /OAuth2
    command: npm start
    volumes:
      - .:/OAuth2
    ports:
      - "48906:3000"
    expose:
      - "3000"
    networks:
      static:
        ipv4_address: 192.168.100.110


networks:
  static:
    external: true
